# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Yong Christopher Tang's Blog
tagline:             'Hello World'
description:         'A personal tech blog powered by github pages'
url:                 http://yongchristophertang.github.io
baseurl:             /
paginate:            50

# About/contact
author:
  name:              Yong (Christopher) Tang
  url:				 http://github.com/yongchristophertang           
  email:             yong.christopher.tang@gmail.com

# Custom vars
version:             1.0.0